details:
  namespace: student8-bookinfo-uat
  image: ghcr.io/poohcid/bookinfo-details
  tag: uat
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 8081
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  host: itkmitl.bookinfo.uat.opsta.net
  path: "/student8/details(/|$)(.*)"
  serviceType: ClusterIP
extraEnv:
  SERVICE_VERSION: v1
  ENABLE_EXTERNAL_BOOK_SERVICE: "true"